<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Username cannot be empty</name>
   <tag></tag>
   <elementGuidId>3ced1d6a-c6e5-4c0b-87e9-a9fbbc91ea54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#spanMessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='spanMessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5257f74a-347f-4ede-9038-eaa2de4c5e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spanMessage</value>
      <webElementGuid>e788f35c-bddc-49b1-9404-920e0ad01d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username cannot be empty</value>
      <webElementGuid>7a284884-214c-4f2f-a15d-ba65f5790e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spanMessage&quot;)</value>
      <webElementGuid>c6ee3fc6-c966-44ec-a324-ed55beb57db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>039945d4-ad0f-46a7-93ad-6afffede467c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spanMessage</value>
      <webElementGuid>dfc96d59-156d-474d-a782-46e67bc7b23a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username cannot be empty</value>
      <webElementGuid>13dddf82-6147-4dc1-a6f5-bc55c0d83b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spanMessage&quot;)</value>
      <webElementGuid>b2361e8a-21f3-4f33-87c0-a43bbb78f97c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='spanMessage']</value>
      <webElementGuid>5f8a4917-6eb6-4877-8920-9c0ea54602aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divLoginButton']/span</value>
      <webElementGuid>a823fe54-fb4a-455a-baa5-7c19e8f98074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::span[1]</value>
      <webElementGuid>1ff001fb-4036-4a46-af2e-baa28a56de40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::span[2]</value>
      <webElementGuid>c7fe455a-a254-4640-8278-e40f4c727804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot your password?'])[1]/preceding::span[1]</value>
      <webElementGuid>4ba937be-cb86-47dd-bcf1-0d4fd71dfa16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Username cannot be empty']/parent::*</value>
      <webElementGuid>4af4a6cd-0a2b-41bf-a836-803813d5e6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span</value>
      <webElementGuid>7eb5250a-f4b2-42c6-8656-21fb6e5da067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'spanMessage' and (text() = 'Username cannot be empty' or . = 'Username cannot be empty')]</value>
      <webElementGuid>3f397170-7081-4e49-9d04-4af77ad3ca80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
